version: "3"

services:

  mailer:
    image: mailhog/mailhog
    container_name: mailer
    restart: ${RESTART}
    networks:
      - net
    ports:
      - ${MAILER_PORT}:8025

  router:
    build:
      context: ./router
      args:
        ssh_pswd: ${ROUTER_SSH_PSWD}
    container_name: router
    restart: ${RESTART}
    networks:
      - net
    ports:
      - ${ROUTER_PORT}:80
      - ${ROUTER_SSH_PORT}:22
    volumes:
      - ${ROUTER_CONFIG_DIR}/router:/etc/nginx/conf.d

networks:

  net:
