version: "3"

services:

  mailer:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mailer
    restart: ${RESTART}
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: ${RESTART}
    environment:
      PMA_ARBITRARY: 1
    volumes:
      - ${PHPMYADMIN_CONFIG_DIR}:/etc/phpmyadmin
    networks:
      - network

  router:
    image: dev-router
    build:
      context: ./images/router
      args:
        ssh_pswd: ${ROUTER_SSH_PSWD}
    container_name: ${COMPOSE_PROJECT_NAME}_router
    depends_on:
      - mailer
      - phpmyadmin
    restart: ${RESTART}
    privileged: true
    networks:
      - network
    ports:
      - ${ROUTER_PORT}:80
      - ${ROUTER_SOCKET_PORT}:8080
      - ${ROUTER_SSL_PORT}:443
      - ${ROUTER_SSH_PORT}:22
    volumes:
      - ${ROUTER_CONFIG_DIR}:/etc/nginx/conf.d
      - ${ROUTER_SSL_DIR}:/etc/ssl/certs

networks:

  network:
