version: "3"

services:

  mailer:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mailer
    restart: ${RESTART}
    networks:
      - net

  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PSWD}
    networks:
      - net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    depends_on:
      - mysql
    restart: ${RESTART}
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${COMPOSE_PROJECT_NAME}_mysql
      PMA_USER: root
      PMA_PASSWORD: ${DB_PSWD}
    volumes:
      - ${PHPMYADMIN_CONFIG_DIR}:/etc/phpmyadmin
    networks:
      - net

  web:
    image: dev-web
    container_name: ${COMPOSE_PROJECT_NAME}_web
    tty: true
    build:
      context: ./web
      args:
        SSH_PSWD: ${WEB_SSH_PSWD}
    depends_on:
      - mysql
    restart: ${RESTART}
    networks:
      - net

  router:
    image: dev-router
    build:
      context: ./router
      args:
        ssh_pswd: ${ROUTER_SSH_PSWD}
    container_name: ${COMPOSE_PROJECT_NAME}_router
    depends_on:
      - mailer
      - phpmyadmin
      - web
    restart: ${RESTART}
    networks:
      - net
    ports:
      - ${ROUTER_PORT}:80
      - ${ROUTER_SSH_PORT}:22
    volumes:
      - ${ROUTER_CONFIG_DIR}:/etc/nginx/conf.d

networks:

  net:
