version: "3"

services:

  mailer:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mailer
    restart: ${RESTART}
    networks:
      - net
    ports:
      - ${MAILER_PORT}:8025

  router:
    image: dev-router
    build:
      context: ./router
      args:
        apt_source: ${APT_SOURCE}
        ssh_pswd: ${ROUTER_SSH_PSWD}
    container_name: ${COMPOSE_PROJECT_NAME}_router
    restart: ${RESTART}
    networks:
      - net
    ports:
      - ${ROUTER_PORT}:80
      - ${ROUTER_SSH_PORT}:22
    volumes:
      - ${ROUTER_CONFIG_DIR}:/etc/nginx/conf.d

networks:

  net:
